// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/nodo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallRequest) Reset() {
	*x = BallRequest{}
	mi := &file_proto_nodo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallRequest) ProtoMessage() {}

func (x *BallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallRequest.ProtoReflect.Descriptor instead.
func (*BallRequest) Descriptor() ([]byte, []int) {
	return file_proto_nodo_proto_rawDescGZIP(), []int{0}
}

func (x *BallRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

type BallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallResponse) Reset() {
	*x = BallResponse{}
	mi := &file_proto_nodo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallResponse) ProtoMessage() {}

func (x *BallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallResponse.ProtoReflect.Descriptor instead.
func (*BallResponse) Descriptor() ([]byte, []int) {
	return file_proto_nodo_proto_rawDescGZIP(), []int{1}
}

func (x *BallResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_nodo_proto protoreflect.FileDescriptor

const file_proto_nodo_proto_rawDesc = "" +
	"\n" +
	"\x10proto/nodo.proto\x12\x05proto\"&\n" +
	"\vBallRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\"(\n" +
	"\fBallResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2B\n" +
	"\vNodoService\x123\n" +
	"\bSendBall\x12\x12.proto.BallRequest\x1a\x13.proto.BallResponseB\bZ\x06/protob\x06proto3"

var (
	file_proto_nodo_proto_rawDescOnce sync.Once
	file_proto_nodo_proto_rawDescData []byte
)

func file_proto_nodo_proto_rawDescGZIP() []byte {
	file_proto_nodo_proto_rawDescOnce.Do(func() {
		file_proto_nodo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_nodo_proto_rawDesc), len(file_proto_nodo_proto_rawDesc)))
	})
	return file_proto_nodo_proto_rawDescData
}

var file_proto_nodo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_nodo_proto_goTypes = []any{
	(*BallRequest)(nil),  // 0: proto.BallRequest
	(*BallResponse)(nil), // 1: proto.BallResponse
}
var file_proto_nodo_proto_depIdxs = []int32{
	0, // 0: proto.NodoService.SendBall:input_type -> proto.BallRequest
	1, // 1: proto.NodoService.SendBall:output_type -> proto.BallResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_nodo_proto_init() }
func file_proto_nodo_proto_init() {
	if File_proto_nodo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_nodo_proto_rawDesc), len(file_proto_nodo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nodo_proto_goTypes,
		DependencyIndexes: file_proto_nodo_proto_depIdxs,
		MessageInfos:      file_proto_nodo_proto_msgTypes,
	}.Build()
	File_proto_nodo_proto = out.File
	file_proto_nodo_proto_goTypes = nil
	file_proto_nodo_proto_depIdxs = nil
}
