// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: nodo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallRequest) Reset() {
	*x = BallRequest{}
	mi := &file_nodo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallRequest) ProtoMessage() {}

func (x *BallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallRequest.ProtoReflect.Descriptor instead.
func (*BallRequest) Descriptor() ([]byte, []int) {
	return file_nodo_proto_rawDescGZIP(), []int{0}
}

func (x *BallRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

type BallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallResponse) Reset() {
	*x = BallResponse{}
	mi := &file_nodo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallResponse) ProtoMessage() {}

func (x *BallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallResponse.ProtoReflect.Descriptor instead.
func (*BallResponse) Descriptor() ([]byte, []int) {
	return file_nodo_proto_rawDescGZIP(), []int{1}
}

func (x *BallResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeatRequest) Reset() {
	*x = BeatRequest{}
	mi := &file_nodo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatRequest) ProtoMessage() {}

func (x *BeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatRequest.ProtoReflect.Descriptor instead.
func (*BeatRequest) Descriptor() ([]byte, []int) {
	return file_nodo_proto_rawDescGZIP(), []int{2}
}

func (x *BeatRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *BeatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeatResponse) Reset() {
	*x = BeatResponse{}
	mi := &file_nodo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatResponse) ProtoMessage() {}

func (x *BeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatResponse.ProtoReflect.Descriptor instead.
func (*BeatResponse) Descriptor() ([]byte, []int) {
	return file_nodo_proto_rawDescGZIP(), []int{3}
}

func (x *BeatResponse) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *BeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BeatResponse) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

type ElectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionRequest) Reset() {
	*x = ElectionRequest{}
	mi := &file_nodo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionRequest) ProtoMessage() {}

func (x *ElectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionRequest.ProtoReflect.Descriptor instead.
func (*ElectionRequest) Descriptor() ([]byte, []int) {
	return file_nodo_proto_rawDescGZIP(), []int{4}
}

func (x *ElectionRequest) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

type ElectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionResponse) Reset() {
	*x = ElectionResponse{}
	mi := &file_nodo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionResponse) ProtoMessage() {}

func (x *ElectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionResponse.ProtoReflect.Descriptor instead.
func (*ElectionResponse) Descriptor() ([]byte, []int) {
	return file_nodo_proto_rawDescGZIP(), []int{5}
}

func (x *ElectionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CoordinatorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoordinatorId int32                  `protobuf:"varint,1,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_nodo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nodo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_nodo_proto_rawDescGZIP(), []int{6}
}

func (x *CoordinatorMessage) GetCoordinatorId() int32 {
	if x != nil {
		return x.CoordinatorId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_nodo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_nodo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_nodo_proto_rawDescGZIP(), []int{7}
}

var File_nodo_proto protoreflect.FileDescriptor

const file_nodo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"nodo.proto\x12\x05proto\"&\n" +
	"\vBallRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\"(\n" +
	"\fBallResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"@\n" +
	"\vBeatRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\fBeatResponse\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\".\n" +
	"\x0fElectionRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\"\"\n" +
	"\x10ElectionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\";\n" +
	"\x12CoordinatorMessage\x12%\n" +
	"\x0ecoordinator_id\x18\x01 \x01(\x05R\rcoordinatorId\"\a\n" +
	"\x05Empty2\xed\x01\n" +
	"\vNodoService\x123\n" +
	"\bSendBall\x12\x12.proto.BallRequest\x1a\x13.proto.BallResponse\x124\n" +
	"\tHeartBeat\x12\x12.proto.BeatRequest\x1a\x13.proto.BeatResponse\x12;\n" +
	"\bElection\x12\x16.proto.ElectionRequest\x1a\x17.proto.ElectionResponse\x126\n" +
	"\vCoordinator\x12\x19.proto.CoordinatorMessage\x1a\f.proto.EmptyB\bZ\x06/protob\x06proto3"

var (
	file_nodo_proto_rawDescOnce sync.Once
	file_nodo_proto_rawDescData []byte
)

func file_nodo_proto_rawDescGZIP() []byte {
	file_nodo_proto_rawDescOnce.Do(func() {
		file_nodo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodo_proto_rawDesc), len(file_nodo_proto_rawDesc)))
	})
	return file_nodo_proto_rawDescData
}

var file_nodo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_nodo_proto_goTypes = []any{
	(*BallRequest)(nil),        // 0: proto.BallRequest
	(*BallResponse)(nil),       // 1: proto.BallResponse
	(*BeatRequest)(nil),        // 2: proto.BeatRequest
	(*BeatResponse)(nil),       // 3: proto.BeatResponse
	(*ElectionRequest)(nil),    // 4: proto.ElectionRequest
	(*ElectionResponse)(nil),   // 5: proto.ElectionResponse
	(*CoordinatorMessage)(nil), // 6: proto.CoordinatorMessage
	(*Empty)(nil),              // 7: proto.Empty
}
var file_nodo_proto_depIdxs = []int32{
	0, // 0: proto.NodoService.SendBall:input_type -> proto.BallRequest
	2, // 1: proto.NodoService.HeartBeat:input_type -> proto.BeatRequest
	4, // 2: proto.NodoService.Election:input_type -> proto.ElectionRequest
	6, // 3: proto.NodoService.Coordinator:input_type -> proto.CoordinatorMessage
	1, // 4: proto.NodoService.SendBall:output_type -> proto.BallResponse
	3, // 5: proto.NodoService.HeartBeat:output_type -> proto.BeatResponse
	5, // 6: proto.NodoService.Election:output_type -> proto.ElectionResponse
	7, // 7: proto.NodoService.Coordinator:output_type -> proto.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nodo_proto_init() }
func file_nodo_proto_init() {
	if File_nodo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodo_proto_rawDesc), len(file_nodo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodo_proto_goTypes,
		DependencyIndexes: file_nodo_proto_depIdxs,
		MessageInfos:      file_nodo_proto_msgTypes,
	}.Build()
	File_nodo_proto = out.File
	file_nodo_proto_goTypes = nil
	file_nodo_proto_depIdxs = nil
}
