// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/nodo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodoService_SendBall_FullMethodName    = "/proto.NodoService/SendBall"
	NodoService_HeartBeat_FullMethodName   = "/proto.NodoService/HeartBeat"
	NodoService_Election_FullMethodName    = "/proto.NodoService/Election"
	NodoService_Coordinator_FullMethodName = "/proto.NodoService/Coordinator"
	NodoService_Replicar_FullMethodName    = "/proto.NodoService/Replicar"
)

// NodoServiceClient is the client API for NodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodoServiceClient interface {
	SendBall(ctx context.Context, in *BallRequest, opts ...grpc.CallOption) (*BallResponse, error)
	HeartBeat(ctx context.Context, in *BeatRequest, opts ...grpc.CallOption) (*BeatResponse, error)
	Election(ctx context.Context, in *ElectionRequest, opts ...grpc.CallOption) (*ElectionResponse, error)
	Coordinator(ctx context.Context, in *CoordinatorMessage, opts ...grpc.CallOption) (*Empty, error)
	Replicar(ctx context.Context, in *Logs, opts ...grpc.CallOption) (*ReplicarResponse, error)
}

type nodoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodoServiceClient(cc grpc.ClientConnInterface) NodoServiceClient {
	return &nodoServiceClient{cc}
}

func (c *nodoServiceClient) SendBall(ctx context.Context, in *BallRequest, opts ...grpc.CallOption) (*BallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BallResponse)
	err := c.cc.Invoke(ctx, NodoService_SendBall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodoServiceClient) HeartBeat(ctx context.Context, in *BeatRequest, opts ...grpc.CallOption) (*BeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeatResponse)
	err := c.cc.Invoke(ctx, NodoService_HeartBeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodoServiceClient) Election(ctx context.Context, in *ElectionRequest, opts ...grpc.CallOption) (*ElectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ElectionResponse)
	err := c.cc.Invoke(ctx, NodoService_Election_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodoServiceClient) Coordinator(ctx context.Context, in *CoordinatorMessage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodoService_Coordinator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodoServiceClient) Replicar(ctx context.Context, in *Logs, opts ...grpc.CallOption) (*ReplicarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicarResponse)
	err := c.cc.Invoke(ctx, NodoService_Replicar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodoServiceServer is the server API for NodoService service.
// All implementations must embed UnimplementedNodoServiceServer
// for forward compatibility.
type NodoServiceServer interface {
	SendBall(context.Context, *BallRequest) (*BallResponse, error)
	HeartBeat(context.Context, *BeatRequest) (*BeatResponse, error)
	Election(context.Context, *ElectionRequest) (*ElectionResponse, error)
	Coordinator(context.Context, *CoordinatorMessage) (*Empty, error)
	Replicar(context.Context, *Logs) (*ReplicarResponse, error)
	mustEmbedUnimplementedNodoServiceServer()
}

// UnimplementedNodoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodoServiceServer struct{}

func (UnimplementedNodoServiceServer) SendBall(context.Context, *BallRequest) (*BallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBall not implemented")
}
func (UnimplementedNodoServiceServer) HeartBeat(context.Context, *BeatRequest) (*BeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (UnimplementedNodoServiceServer) Election(context.Context, *ElectionRequest) (*ElectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Election not implemented")
}
func (UnimplementedNodoServiceServer) Coordinator(context.Context, *CoordinatorMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Coordinator not implemented")
}
func (UnimplementedNodoServiceServer) Replicar(context.Context, *Logs) (*ReplicarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replicar not implemented")
}
func (UnimplementedNodoServiceServer) mustEmbedUnimplementedNodoServiceServer() {}
func (UnimplementedNodoServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodoServiceServer will
// result in compilation errors.
type UnsafeNodoServiceServer interface {
	mustEmbedUnimplementedNodoServiceServer()
}

func RegisterNodoServiceServer(s grpc.ServiceRegistrar, srv NodoServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodoService_ServiceDesc, srv)
}

func _NodoService_SendBall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoServiceServer).SendBall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoService_SendBall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoServiceServer).SendBall(ctx, req.(*BallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodoService_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoServiceServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoService_HeartBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoServiceServer).HeartBeat(ctx, req.(*BeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodoService_Election_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoServiceServer).Election(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoService_Election_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoServiceServer).Election(ctx, req.(*ElectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodoService_Coordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoServiceServer).Coordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoService_Coordinator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoServiceServer).Coordinator(ctx, req.(*CoordinatorMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodoService_Replicar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Logs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoServiceServer).Replicar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoService_Replicar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoServiceServer).Replicar(ctx, req.(*Logs))
	}
	return interceptor(ctx, in, info, handler)
}

// NodoService_ServiceDesc is the grpc.ServiceDesc for NodoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NodoService",
	HandlerType: (*NodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendBall",
			Handler:    _NodoService_SendBall_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _NodoService_HeartBeat_Handler,
		},
		{
			MethodName: "Election",
			Handler:    _NodoService_Election_Handler,
		},
		{
			MethodName: "Coordinator",
			Handler:    _NodoService_Coordinator_Handler,
		},
		{
			MethodName: "Replicar",
			Handler:    _NodoService_Replicar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/nodo.proto",
}
